### ISSUE TITLE
Move the examples project to a repository

### ISSUE THREAD

**Issue by sebas5384** [recidive/choko#262]
In this way we don't confuse users (mean developers), and their are gonna have a perfect example of how their project actually is going to look.

Thoughts?

**Comment by jardix22** [comment]
:+1:

**Comment by recidive** [comment]
Yes, that's something we talked at the MVP meeting.

I think we should move the example project to a separate project and move the default app from `/applications/default` to `/core` or something else. What do you think?

**Comment by sebas5384** [comment]
Completely agree on that @recidive :)

**Comment by recidive** [comment]
Choko example is already on [it's own repository](https://github.com/recidive/choko-example). I've opened #271 for moving the default application to /core.
